#!c:\Users\Botond\Documents\Uni\UniWien\Subjects\2024W\DAP\personalized-education\personalized_education\Scripts\python.exe
# -*- coding: UTF-8 -*-
from __future__ import print_function, division, absolute_import

from numba.misc.numba_entry import main

if __name__ == "__main__":
    main()
